create database comic;

use comic;

INSERT INTO comic (category, description, discount_percent, imagesrc, link_comic, price, publisher, title) VALUES
-- SPIDERMAN
('marvel', 'En este primer volumen, Hobie Brown obtiene los poderes de un héroe arácnido y los mezcla con una actitud punk explosiva para desafiar un sistema corrupto que controla Nueva York. Con su guitarra, su estilo único y su espíritu rebelde, Spider-Punk demuestra que hasta un joven común puede encender la chispa de la revolución.', NULL, '/recursos/spiderman/photo_4917961266337786754_y.jpg', 'archivosComics/marvelComics/spiderman/SpiderPunk.pdf', 77.70, 'Marvel', 'Spider-Punk'),
('marvel', 'Miguel O’Hara vive en un futuro dominado por corporaciones que controlan cada rincón de Nueva York. Un experimento fallido le otorga poderes arácnidos sobrehumanos y un traje futurista, convirtiéndolo en Spider-Man 2099. Entre tecnología avanzada, enemigos implacables y una ciudad corrupta, deberá usar su ingenio y habilidades únicas para luchar por la justicia y demostrar que incluso en un futuro sombrío, un héroe puede marcar la diferencia.', NULL, '/recursos/spiderman/photo_5035358807189991169_y.jpg', 'archivosComics/marvelComics/spiderman/SpiderMan2099.pdf', 105.00, 'Marvel', 'Spider-Man 2099'),
('marvel', 'Miles Morales es un adolescente común que descubre que posee poderes arácnidos similares a los de Spider-Man. Entre equilibrar la escuela, la familia y la vida como joven héroe, Miles aprende a asumir la responsabilidad que viene con sus habilidades. Con agilidad, ingenio y un estilo único, se enfrenta a villanos peligrosos y a desafíos inesperados, demostrando que cualquiera, sin importar su origen, puede ser un verdadero Spider-Man.', NULL, '/recursos/spiderman/photo_5049085097466244912_y.jpg', 'archivosComics/marvelComics/spiderman/SpiderManMilesMorales.pdf', 85.00, 'Marvel', 'Spider-Man: Miles Morales Vol.1'),
('marvel', 'Ben Reilly, el clon de Peter Parker, asume la identidad de Scarlet Spider para proteger Nueva York con sus propios valores y estilo. Entre villanos clásicos y nuevas amenazas, Ben lucha por encontrar su lugar como héroe mientras demuestra que ser diferente no significa ser menos. Con agilidad, astucia y un traje rojo distintivo, Scarlet Spider enfrenta la justicia con determinación y corazón, dejando su propia huella en el legado arácnido.', NULL, '/recursos/spiderman/photo_5154894941107891602_y.jpg', 'archivosComics/marvelComics/spiderman/scarletSpider.pdf', 95.00, 'Marvel', 'Ben Rilley: Spider Scarlet'),

-- 4 FANTASTICOS
('marvel', 'Los 4 Fantásticos se adentran en la misteriosa y peligrosa Zona Negativa, un universo paralelo lleno de desafíos, enemigos desconocidos y peligros que amenazan la realidad misma. Reed Richards, Sue Storm, Johnny Storm y Ben Grimm deberán unir su ingenio, poderes y valentía para sobrevivir y proteger no solo su mundo, sino también el delicado equilibrio entre dimensiones. Acción, ciencia y aventuras interdimensionales te esperan en esta trepidante historia.', NULL, '/recursos/4fantasticos/photo_4942934619968350778_y.jpg', 'archivosComics/marvelComics/4Fantasticos/4FantasticosNegativeZone.pdf', 75.20, 'Marvel', 'Los 4 Fantásticos: Negative Zone'),
('marvel', 'Reed, Sue, Johnny y Ben dejan por un momento los peligros cósmicos para embarcarse en un viaje lleno de diversión, sorpresas y encuentros inesperados. Entre risas, desafíos y algún que otro enfrentamiento con villanos, esta historia muestra el lado más humano y divertido del equipo, demostrando que incluso los héroes necesitan un descanso… y una buena aventura en la carretera.', NULL, '/recursos/4fantasticos/photo_4958791153893879460_y.jpg', 'archivosComics/marvelComics/4Fantasticos/4FantasticosRoadTrip.pdf', 66.00, 'Marvel', 'Los 4 Fantásticos: Road Trip'),
('marvel', 'Una tragedia sacude a los 4 Fantásticos: Johnny Storm, la Antorcha Humana, enfrenta un destino inesperado que pone a prueba al equipo y su unión. Reed, Sue y Ben deben lidiar con la pérdida, mientras continúan luchando contra amenazas que ponen en riesgo a la humanidad. Esta intensa historia combina acción, emoción y drama, mostrando que incluso los héroes más poderosos enfrentan momentos de vulnerabilidad y dolor.', NULL, '/recursos/4fantasticos/photo_5012949987121802585_y.jpg', 'archivosComics/marvelComics/4Fantasticos/4FantasticosLaMuerteDeLaAntorchaHumana.pdf', 150.00, 'Marvel', 'Los 4 Fantásticos: La Muerte de la Antorcha Humana'),
('marvel', 'Celebra un siglo de aventuras con Los 4 Fantásticos en su edición del 100 aniversario. Reed, Sue, Johnny y Ben recorren sus historias más icónicas, enfrentando villanos clásicos, desafíos épicos y momentos que definieron su legado. Esta edición especial reúne acción, nostalgia y homenaje a un equipo que ha marcado generaciones, demostrando que la familia más increíble de Marvel sigue siendo eterna.', NULL, '/recursos/4fantasticos/photo_5143628296997678853_y.jpg', 'archivosComics/marvelComics/4Fantasticos/4Fantasticos100Aniversario.pdf', 65.00, 'Marvel', 'Los 4 Fantásticos 100° Aniversario'),

-- X-MEN
('marvel', 'Los mutantes más poderosos de la historia llegan a un punto crítico en X-Men: First Class – Finales. Charles Xavier, Erik Lehnsherr y su equipo enfrentan decisiones que definirán el destino de los humanos y mutantes por igual. Con alianzas tensas, traiciones inesperadas y batallas épicas, esta historia muestra los inicios de los X-Men y cómo los cimientos de su legado se forjan en medio del conflicto y la lucha por la paz.', NULL, '/recursos/Xmen/xmenFinalesPrimeraGeneracion.jpg', 'archivosComics/marvelComics/xmen/xmenPrimeraClaseFinales.pdf', 70.00, 'Marvel', 'X-Men: First Class Finales'),
('marvel', 'Los X-Men regresan con fuerza en X-Men ’97, continuando la lucha por la coexistencia entre mutantes y humanos. Nuevas amenazas emergen mientras viejos aliados y enemigos se enfrentan a desafíos que ponen a prueba su fuerza, lealtad y valores. Acción, drama y aventura se combinan en esta saga que revitaliza el universo mutante, demostrando que la lucha por la justicia nunca termina.', NULL, '/recursos/Xmen/xmen97.jpg', 'archivosComics/marvelComics/xmen/xMen97.pdf', 50.00, 'Marvel', 'X-Men 97\''),
('marvel', 'En X-Men: House of XCII, los mutantes se enfrentan a un futuro alternativo lleno de misterio, poder y traición. Charles Xavier y su equipo deben navegar entre alianzas inciertas y enemigos inesperados para proteger tanto a mutantes como a humanos. Con acción intensa, secretos revelados y decisiones que cambian el destino del universo mutante, esta historia muestra que el legado de los X-Men está lleno de retos que van más allá de los poderes.', NULL, '/recursos/Xmen/xmenHouseOfXCII.jpg', 'archivosComics/marvelComics/xmen/xMenHouseOfXCII.pdf', 150.00, 'Marvel', 'X-Men House Of XCII'),
('marvel', 'Cuando los X-Men se cruzan con Wolverine, la acción y el peligro se multiplican. Entre combates contra enemigos mortales y conflictos internos, Logan demuestra por qué es uno de los mutantes más temidos y respetados. Con estrategias arriesgadas, enfrentamientos épicos y el espíritu indomable de Wolverine, esta historia une fuerza, ingenio y determinación para proteger tanto a mutantes como a humanos.', NULL, '/recursos/Xmen/xmenAndTheWolverine.jpg', 'archivosComics/marvelComics/xmen/xMenAndWolverine.pdf', 88.00, 'Marvel', 'X-Men and The Wolverine'),

-- AVENGERS
('marvel', 'En el Volumen 7, los Avengers enfrentan su desafío más grande hasta ahora. Con enemigos formidables amenazando la Tierra, héroes como Iron Man, Capitán América, Thor y Hulk deben unir fuerzas, ingenio y valentía para salvar el planeta. Entre batallas épicas, estrategias inesperadas y momentos heroicos, esta entrega demuestra por qué los Avengers son verdaderamente los héroes más poderosos del planeta.', NULL, '/recursos/avengers/AvengersVol7.jpg', 'archivosComics/marvelComics/avengers/AvengersLosHeroesMasPoderososDelPlaneta.pdf', 91.00, 'Marvel', 'Avengers: Los Heroés más Poderosos del Planeta Vol. 7'),
('marvel', 'Los Avengers se enfrentan a una amenaza imparable en Rage of Ultron. El villano cibernético más peligroso ha despertado, y solo la unión de héroes como Iron Man, Capitán América, Thor y Hulk puede detener su plan de destrucción total. Con acción intensa, estrategias audaces y momentos de tensión al límite, esta historia muestra que incluso los héroes más poderosos deben superar sus límites para proteger al mundo.', NULL, '/recursos/avengers/avengersRageOfUltron.jpg', 'archivosComics/marvelComics/avengers/AvengersRageOfUltron.pdf', 83.00, 'Marvel', 'Avengers: Rage of Ultron'),
('marvel', 'En Avengers: Millennium, los héroes más poderosos de la Tierra se enfrentan a un nuevo enemigo que amenaza con cambiar el curso de la historia. Iron Man, Capitán América, Thor, Hulk y el resto del equipo deberán unir fuerzas como nunca antes, enfrentando desafíos que ponen a prueba su valentía, ingenio y unidad. Una aventura épica llena de acción, peligro y heroísmo que marca un hito en el legado de los Avengers.', NULL, '/recursos/avengers/avengersMilenium.jpg', 'archivosComics/marvelComics/avengers/AvengersMilenium.pdf', 83.00, 'Marvel', 'Avengers: Milenium'),
('marvel', 'En Secret Avengers Vol. 1, un equipo selecto de héroes opera desde las sombras para enfrentar amenazas que el mundo ni siquiera conoce. Con misiones encubiertas, estrategias arriesgadas y decisiones que podrían cambiar el destino de la humanidad, estos Avengers muestran un lado más oscuro y audaz del heroísmo. Acción, intriga y secretos se mezclan en esta historia donde la verdadera fuerza no siempre se muestra a la luz del día.', NULL, '/recursos/avengers/secretAvengersVol1.jpg', 'archivosComics/marvelComics/avengers/secretAvengers.pdf', 110.00, 'Marvel', 'Secret Avengers Vol. 1'),

-- THE FLASH
('dc', 'En Flashpoint, Barry Allen despierta en un mundo completamente alterado donde nada es como lo conoce. Sin sus poderes y enfrentando héroes transformados por la guerra, deberá usar su ingenio y valentía para restaurar la línea temporal. Entre conflictos épicos y decisiones que cambian el destino del planeta, Flash demuestra que incluso un héroe común puede marcar la diferencia en un mundo al borde del colapso.', NULL, '/recursos/the flash/photo_5132069642355976623_y.jpg', 'archivosComics/DCcomics/flash/theFlashFlashpoint.pdf', 57.70, 'DC', 'The Flash: Flashpoint'),
('dc', 'En The Fastest Man Alive, Barry Allen usa su velocidad sobrehumana para proteger Central City de criminales y amenazas que nadie más puede detener. Con ingenio, determinación y un sentido de justicia inquebrantable, Flash demuestra que la verdadera velocidad no solo se mide en kilómetros por hora, sino en la capacidad de actuar rápido y cambiar el destino de quienes lo necesitan.', NULL, '/recursos/the flash/photo_5183661712933497268_y.jpg', 'archivosComics/DCcomics/flash/theFlashTheFastestManAlive.pdf', 57.70, 'DC', 'The Flash: The Fastest Man Alive'),
('dc', 'En Flash War Vol. 8, Barry Allen enfrenta uno de sus mayores desafíos cuando viejos aliados se convierten en rivales y la ciudad corre peligro por un conflicto que amenaza con destruir la línea temporal. Con su velocidad incomparable, ingenio y determinación, Flash demuestra que incluso en medio del caos más rápido, un héroe decidido puede restaurar el orden y proteger a quienes ama.', NULL, '/recursos/the flash/photo_4902577668441090547_y.jpg', 'archivosComics/DCcomics/flash/theFlashFlashWar.pdf', 74.70, 'DC', 'The Flash: Flash War Vol.8'),
('dc', 'En La Guerra de un Minuto, Barry Allen se enfrenta a un conflicto que amenaza con alterar el tiempo y poner en peligro a toda Central City. Con su velocidad sobrehumana y su ingenio, Flash deberá superar enemigos implacables y tomar decisiones en fracciones de segundo para proteger a los inocentes. Esta historia demuestra que, incluso en el instante más breve, un héroe puede cambiar el destino de muchos.', NULL, '/recursos/the flash/photo_4909055965182143464_y.jpg', 'archivosComics/DCcomics/flash/theFlashGuerraDeUnMinuto.pdf', 64.00, 'DC', 'The Flash: La Guerra de un Minuto'),

-- SUPERMAN
('dc', 'En La Muerte de Superman, el Hombre de Acero enfrenta a un enemigo imparable que amenaza con destruir Metrópolis y todo lo que ama. Con valentía, sacrificio y un sentido inquebrantable de justicia, Superman demuestra que incluso los héroes más poderosos deben enfrentarse a sus límites para proteger a la humanidad. Una historia épica que redefine el legado del último hijo de Krypton.', NULL, '/recursos/superman/la muerte de superman.jpg', 'archivosComics/DCcomics/superman/laMuerteDeSuperman.pdf', 104.00, 'DC', 'La Muerte de Superman'),
('dc', 'En Superman: Erradicación, Clark Kent se enfrenta a una amenaza que pone en riesgo no solo Metrópolis, sino a toda la humanidad. Con su fuerza sobrehumana, inteligencia y determinación, Superman debe detener un peligro implacable antes de que sea demasiado tarde, demostrando que incluso el héroe más poderoso necesita valor y estrategia para salvar el mundo.', NULL, '/recursos/superman/superman erradicacion.jpg', 'archivosComics/DCcomics/superman/supermanErradicacion.pdf', 94.00, 'DC', 'Superman: Erradicación'),
('dc', 'En New Krypton Vol. 3, Superman se enfrenta a los desafíos de un nuevo hogar kryptoniano en la Tierra, donde alianzas y lealtades se ponen a prueba. Entre conflictos inesperados y decisiones cruciales, Clark Kent demuestra que proteger tanto a su planeta adoptivo como a su gente requiere no solo fuerza, sino también sabiduría y corazón.', NULL, '/recursos/superman/superman new Krypton vol3.jpg', 'archivosComics/DCcomics/superman/supermanNewKrypton.pdf', 74.00, 'DC', 'Superman: New Krypton Vol. 3'),
('dc', 'En Tierra 1 Vol. 3, Clark Kent enfrenta los desafíos de un mundo moderno donde la justicia y la verdad no siempre son claras. Con valentía, ingenio y un compromiso inquebrantable, Superman lucha por proteger a los inocentes y demostrar que incluso en tiempos complicados, un héroe puede marcar la diferencia.', NULL, '/recursos/superman/superman tierra 1 vol3.jpg', 'archivosComics/DCcomics/superman/supermanTierra1.pdf', 52.20, 'DC', 'Superman: Tierra 1 Vol. 3'),

-- LINTERNA VERDE
('dc', 'En Tierra 1 Vol. 1, Hal Jordan descubre el poder de su anillo de Linterna Verde y la responsabilidad de proteger el universo. Con coraje, ingenio y un fuerte sentido de justicia, se enfrenta a enemigos implacables y desafíos que ponen a prueba su determinación, demostrando que incluso un héroe recién formado puede brillar en medio de la oscuridad.', NULL, '/recursos/Linterna verde/linterna verde tierra 1 vol 1.jpg', 'archivosComics/DCcomics/linternaVerde/linternaVerdeTierra1Vol1.pdf', 152.20, 'DC', 'Linterna Verde: Tierra 1 Vol. 1'),
('dc', 'En Tierra 1 Vol. 2, Hal Jordan continúa su viaje como Linterna Verde, enfrentando nuevas amenazas que desafían su valentía y su habilidad para mantener el equilibrio en el universo. Con su anillo como arma y su voluntad como guía, demuestra que incluso en situaciones imposibles, un héroe decidido puede iluminar la oscuridad y proteger a los inocentes.', NULL, '/recursos/Linterna verde/linterna verde tierra 1 vol 2.jpg', 'archivosComics/DCcomics/linternaVerde/linternaVerdeTierra1Vol2.pdf', 68.90, 'DC', 'Linterna Verde: Tierra 1 Vol. 2'),
('dc', 'En Linterna Verde Vol. 4, Hal Jordan enfrenta nuevas amenazas que ponen a prueba su voluntad y determinación como protector del universo. Con su anillo como arma y su coraje como guía, demuestra que incluso en medio del peligro más intenso, un héroe decidido puede iluminar la oscuridad y proteger a quienes lo necesitan.', NULL, '/recursos/Linterna verde/linterna verde vol 4.jpg', 'archivosComics/DCcomics/linternaVerde/linternaVerdeVol4.pdf', 188.90, 'DC', 'Linterna Verde Vol. 4'),
('dc', 'En Daño Colateral, Guy Gardner enfrenta una misión peligrosa que pondrá a prueba tanto su fuerza como su determinación. Entre conflictos explosivos y decisiones difíciles, demuestra que incluso un héroe con carácter explosivo puede actuar con coraje y proteger a quienes dependen de él.', NULL, '/recursos/Linterna verde/guy garden daño colateral.jpg', 'archivosComics/DCcomics/linternaVerde/guyGardnerDañoColateral.pdf', 188.80, 'DC', 'Guy Garden: Daño Colateral'),

-- BATMAN
('dc', 'En Archivos Secretos, Batman revela casos y misterios inéditos de Gotham que nunca antes habían sido documentados. Entre investigaciones meticulosas y enfrentamientos con criminales peligrosos, Bruce Wayne demuestra que la verdadera fuerza de un héroe reside en su inteligencia, estrategia y capacidad para proteger a los inocentes incluso en las sombras.', NULL, '/recursos/batman/batman archivos secretos.jpg', 'archivosComics/DCcomics/batman/batmanArchivosSecretos.pdf', 77.00, 'DC', 'Batman: Archivos Secretos'),
('dc', 'En Batman Beyond Vol. 1, un nuevo vigilante toma el manto de Batman en una Gotham futurista. Con tecnología avanzada y un sentido de justicia inquebrantable, el joven héroe enfrenta criminales modernos y peligros desconocidos, demostrando que incluso en un mundo cambiante, siempre hay lugar para un protector decidido.', NULL, '/recursos/batman/batman beyond.jpg', 'archivosComics/DCcomics/batman/batmanBeyondVol1.pdf', 77.00, 'DC', 'Batman Beyond Vol. 1'),
('dc', 'En Batman: El Regreso del Señor de la Noche, Batman vuelve a las sombras de Gotham para enfrentar una amenaza que pone a la ciudad al borde del caos. Con astucia, experiencia y un sentido inquebrantable de justicia, demuestra que incluso después de la oscuridad, un héroe decidido puede restaurar el orden y proteger a los inocentes.', NULL, '/recursos/batman/batman el regreso del seños de la noche.jpg', 'archivosComics/DCcomics/batman/batmanElRegresoDelSeñorDeLaNoche.pdf', 87.70, 'DC', 'Batman: El Regreso del Señor de la Noche'),
('dc', 'En Joker War, Gotham City se enfrenta al caos absoluto cuando el Joker desata su plan más destructivo hasta la fecha. Batman debe usar todo su ingenio, estrategia y valentía para detener al príncipe del crimen y proteger a la ciudad. Esta historia demuestra que incluso frente al enemigo más impredecible, la determinación de un héroe puede marcar la diferencia.', NULL, '/recursos/batman/batman joker war.jpg', 'archivosComics/DCcomics/batman/batmanJokerWar.pdf', 65.50, 'DC', 'Batman: Joker War'),

-- DESCUENTO
('descuento', 'Danny Rand, heredero de una fortuna, regresa al mundo tras años de entrenamiento en la mística ciudad de K’un-Lun. Allí dominó las artes marciales y obtuvo el poder del Puño de Hierro, canalizando la energía del dragón Shou-Lao. Ahora, como Iron Fist, debe equilibrar su vida entre empresario y guerrero, enfrentando enemigos mortales, antiguas rivalidades y la responsabilidad de portar un legado que trasciende generaciones.', 18, '/recursos/descuentos/ironFist vol1.jpg', 'archivosComics/descuentos/IronFistVol1.pdf', 87.10, 'Marvel', 'Iron Fist Vol. 01'),
('descuento', 'Marc Spector, el enigmático Moon Knight, se adentra en la Ciudad de los Muertos tras aceptar una misión que lo conecta con lo sobrenatural. Con el poder del dios Khonshu como guía, debe enfrentarse a espíritus vengativos, secretos del más allá y a sus propios demonios internos. En un escenario donde la frontera entre la vida y la muerte se desdibuja, el Puño de Khonshu demostrará que incluso en la oscuridad más profunda, la justicia puede abrirse camino.', 12, '/recursos/descuentos/moonKnight city of the dead.jpg', 'archivosComics/descuentos/moonKnightCityOfTheDead.pdf', 94.00, 'Marvel', 'Moon Knight: City of the Dead'),
('descuento', 'En un universo alternativo, Kal-El no llega a la Tierra siendo un bebé, sino como un adolescente marcado por la caída de Kryptón. Adoptado en Smallville, descubre sus poderes en medio de un mundo controlado por corporaciones y sistemas de opresión. Con un traje guiado por inteligencia artificial y un fuerte sentido de justicia, se convierte en Superman, enfrentando no solo amenazas físicas, sino también la desigualdad y la corrupción. En esta nueva visión, el Último Hijo de Kryptón lucha por demostrar que la esperanza puede sobrevivir incluso en el futuro más oscuro.', 15, '/recursos/descuentos/absoluteSuperman.jpg', 'archivosComics/descuentos/absoluteSuperman.pdf', 104.00, 'DC', 'The Absolute Superman'),
('descuento', 'Cuando el rey de Wakanda y el mercenario más impredecible del mundo se cruzan, el choque es inevitable. Black Panther defiende con disciplina y estrategia el legado de su nación, mientras Deadpool irrumpe con su humor caótico y métodos poco convencionales. Entre secretos ocultos, combates explosivos y un choque de filosofías, ambos héroes descubrirán que a veces el mayor enemigo puede ser también el aliado más inesperado.', 20, '/recursos/descuentos/blackPhanter vs Deadpool.jpg', 'archivosComics/descuentos/blackPantherVSDeadpool.pdf', 150.00, 'Marvel', 'Black Panther vs Deadpool'),
('descuento', 'Arthur Curry, rey de Atlantis, vive un viaje de redescubrimiento y dolor bajo la pluma de Peter David. Tras perder su mano en combate y reemplazarla con un arpón, adopta una apariencia más salvaje y un carácter implacable. Entre intrigas políticas, amenazas míticas y batallas contra antiguos dioses, Aquaman debe reconciliar su herencia atlante con su lado humano. En un mundo que lo teme y lo subestima, demostrará que no es solo el señor de los mares, sino un héroe capaz de enfrentar cualquier tormenta.', 10, '/recursos/descuentos/aquaman vol1.jpg', 'archivosComics/descuentos/aquamanVol1.pdf', 72.00, 'DC', 'Aquaman Vol. 01'),
('descuento', 'Teth-Adam, un guerrero marcado por la tragedia y la ira, despierta en un mundo moderno que no entiende ni respeta sus códigos. Con el poder de los dioses egipcios corriendo por sus venas, se convierte en Black Adam, un campeón tan temido como venerado. Enfrentado a héroes, dictadores y deidades, deberá decidir si es un destructor implacable o un líder destinado a forjar un nuevo futuro. Una saga épica donde mito, poder y destino colisionan en la historia definitiva del antihéroe eterno.', 25, '/recursos/descuentos/black adam the dark age.jpg', 'archivosComics/descuentos/blackAdamAgeDeluxeEdition.pdf', 102.50, 'DC', 'Black Adam Age Deluxe Edition'),
('descuento', 'Billy Batson, un joven huérfano con un corazón noble, descubre que con solo pronunciar la palabra mágica ''Shazam'' puede transformarse en un héroe con el poder de los dioses antiguos. Entre la inocencia de un adolescente y la fuerza de un campeón, deberá aprender a equilibrar su vida cotidiana con la responsabilidad de ser un protector del mundo. En este inicio de saga, Shazam enfrenta enemigos mágicos y pruebas que pondrán a prueba no solo sus poderes, sino también la grandeza de su espíritu.', 22, '/recursos/descuentos/shazamVol4.jpg', 'archivosComics/descuentos/shazamVol4.pdf', 140.10, 'DC', 'Shazam Vol. 04'),
('descuento', 'Miguel O’Hara vive en un futuro gobernado por corporaciones que dominan hasta el último rincón de Nueva York. Un experimento fallido le otorga habilidades arácnidas sobrehumanas y un traje tecnológico, convirtiéndolo en Spider-Man 2099. Entre avances científicos, enemigos implacables y una ciudad sumida en la corrupción, deberá usar su ingenio y valentía para luchar por la justicia y demostrar que incluso en un futuro sombrío, un héroe puede marcar la diferencia.', 15, '/recursos/descuentos/Spider-Man 2099.jpg', 'archivosComics/descuentos/SpiderMan2099.pdf', 80.80, 'Marvel', 'Spider-Man 2099'),

-- MÁS VENDIDOS
('mas-vendido', 'Ben Reilly: Scarlet Spider Vol. 2 sigue las aventuras del clon de Spider-Man en Las Vegas, enfrentando dilemas morales y enemigos letales.', NULL, 'https://cdn.marvel.com/u/prod/marvel/i/mg/4/40/593991f482d4c/clean.jpg', 'archivosComics/masVendidos/scarletSpider.pdf', 184.40, 'Marvel', 'Ben Rilley: Scarlet Spider Vol. 2'),
('mas-vendido', 'Los 4 Fantásticos vs Dr. Doom presenta un épico enfrentamiento entre la Primera Familia de Marvel y su archienemigo.', NULL, '/recursos/4fantasticos/4 fantasticos.jpg', 'archivosComics/masVendidos/4fantasticosVSdrDoom.pdf', 75.50, 'Marvel', 'Los 4 Fantásticos vs Dr. Doom'),
('mas-vendido', 'X-Men: Primera Generación relata los orígenes del equipo liderado por el Profesor X y su rivalidad con Magneto.', NULL, 'https://www.geekmi.news/export/sites/debate/img/2023/11/13/clean-504.jpg_1318211660.jpg', 'archivosComics/masVendidos/xmenPrimeraGeneracion.pdf', 70.00, 'Marvel', 'X-Men: Primera Generación'),
('mas-vendido', 'Moon Knight: Puño de Khonshu muestra a Marc Spector, el vigilante con múltiples personalidades que recibe el poder de un dios egipcio.', NULL, 'https://cdn.marvel.com/u/prod/marvel/i/mg/7/03/667c7744d0240/clean.jpg', 'archivosComics/masVendidos/moonKnightKhonzu.pdf', 120.00, 'Marvel', 'Moon Knight: Puño de Khonshu'),
('mas-vendido', 'Guardianes de la Galaxia Vol. 1 reúne a un grupo disfuncional de héroes intergalácticos para salvar el universo.', NULL, 'https://sm.ign.com/ign_es/screenshot/default/guardians-of-the-galaxy-1-new-lineup-cover-1253384_4m33.jpg', 'archivosComics/masVendidos/guardianesDeLaGalaxia.pdf', 120.00, 'Marvel', 'Guardianes de la Galaxia Vol. 1'),
('mas-vendido', 'Superior Spider-Man Vol. 1 inicia la etapa donde el Doctor Octopus toma el control del cuerpo de Peter Parker.', NULL, 'https://m.media-amazon.com/images/I/817DOuhaNFL._UF1000,1000_QL80_.jpg', 'archivosComics/masVendidos/superiorSpiderMan.pdf', 114.40, 'Marvel', 'Superior Spider-Man Vol. 1'),
('mas-vendido', 'Deadpool: Bad Blood Vol. 3 trae al mercenario bocazas enfrentando a un nuevo enemigo con su estilo caótico y sarcástico.', NULL, 'https://cdn.marvel.com/u/prod/marvel/i/mg/6/40/62d04547da35f/clean.jpg', 'archivosComics/masVendidos/deadpoolBadBlood.pdf', 73.30, 'Marvel', 'Deadpool: Bad Blood Vol. 3'),
('mas-vendido', 'Nova: Annihilation 2099 narra una batalla cósmica en un futuro devastado donde Nova lucha por mantener la esperanza.', NULL, 'https://cdn.marvel.com/u/prod/marvel/i/mg/e/d0/66797569517d4/clean.jpg', 'archivosComics/masVendidos/novaAniquilacion.pdf', 200.00, 'Marvel', 'Nova: Annihilation 2099'),
('mas-vendido', 'The Punisher Vol. 12 sigue a Frank Castle en su brutal guerra contra el crimen organizado.', NULL, '/recursos/thePunisher.jpg', 'archivosComics/masVendidos/thePunisher.pdf', 70.50, 'Marvel', 'The Punisher Vol. 12'),
('mas-vendido', 'Ant-Man Vol. 2 presenta nuevas aventuras de Scott Lang, equilibrando su rol como héroe diminuto y padre.', NULL, '/recursos/ant-manVol2.jpg', 'archivosComics/masVendidos/antMan.pdf', 145.00, 'Marvel', 'Ant-Man Vol. 2');

INSERT INTO user (
    cover_imageurl, email, password, profile_picture, user_bio, user_name, role
) VALUES (
    'http://localhost:8080/recursos/portadas/portada4.jpeg',
    'adminJuFer@gmail.com',
    '$2a$10$Scaxh5pbOy25XF/YZKvXwe2AZpV4v8DGbqRvrXMgfeEiY2JPkJRLC', -- del 1 al 6
    'http://localhost:8080/recursos/avatares/adminIcon.jpeg',
    'Administrador de Comic Forge con acceso completo al sistema.',
    'Junior',
    'admin'
);

INSERT INTO user (
    cover_imageurl, email, password, profile_picture, user_bio, user_name, role
) VALUES (
    'http://localhost:8080/recursos/portadas/portada4.jpeg',
    'adminCristian@gmail.com',
    '$2a$10$Scaxh5pbOy25XF/YZKvXwe2AZpV4v8DGbqRvrXMgfeEiY2JPkJRLC', -- del 1 al 6
    'http://localhost:8080/recursos/avatares/adminIcon.jpeg',
    'Administrador de Comic Forge con acceso completo al sistema.',
    'Cristian',
    'admin'
);

INSERT INTO user (
    cover_imageurl, email, password, profile_picture, user_bio, user_name, role
) VALUES (
    'http://localhost:8080/recursos/portadas/portada4.jpeg',
    'prueba@gmail.com',
    '$2a$10$Scaxh5pbOy25XF/YZKvXwe2AZpV4v8DGbqRvrXMgfeEiY2JPkJRLC', -- del 1 al 6
    'http://localhost:8080/recursos/avatares/Moon%20Knight%20icon.jpeg',
    'Amante de los comics de Marvel y mi equipo fav es los xmen, the flash mi personaje favorito',
    'JuFer',
    'cliente'
);
