spring.application.name=ComicForge
spring.datasource.url=jdbc:mysql://localhost:3306/comic
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.servlet.multipart.max-file-size=250MB
spring.servlet.multipart.max-request-size=250MB
spring.security.oauth2.client.registration.google.client-id=797635612467-ufe03thk7cl9n0cnj9svodo0upae1vtp.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google
